### ISSUE TITLE
How do I set the TimeoutExpired?

### ISSUE THREAD

**Issue by peter-lawrey** [nst/JSONTestSuite#24]
I have the latest version but when I run

$ python3 run_tests.py 

I get

```
('--', '/home/peter/git/JSONTestSuite/parsers/test_Bash_JSON/JSON.sh')
Traceback (most recent call last):
  File "run_tests.py", line 646, in <module>
    run_tests(restrict_to_path)
  File "run_tests.py", line 292, in run_tests
    except subprocess.TimeoutExpired:
AttributeError: 'module' object has no attribute 'TimeoutExpired'
```

**Comment by nst** [comment]
I think you need Python 3.3 https://docs.python.org/3/library/subprocess.html
